export const PUBLICATION_URL = "https://prints.touchstoneassay.com/";

/**
 * Generated by scripts/sync-marketing-print.mjs from data/prints/latest.json — do not hand-edit.
 * Replace only by publishing a new print; this file is regenerated on every marketing build.
 * Source print: 2026-08-18.
 */
export const CURRENT_PRINT = {
  value: "0.0015",
  date: "2026-08-18",
  status: "PROVISIONAL",
} as const;
