// The `Env` type itself is intentionally NOT declared here: `worker-configuration.d.ts`
// (generated by `wrangler types`, run again after any wrangler.jsonc binding change — see
// README.md) declares it globally from wrangler.jsonc's actual bindings/vars, and augments the
// `Cloudflare.Env` namespace the `agents` package's base classes constrain their generic `Env`
// parameter against. A hand-written duplicate here silently drifted out of sync with that
// constraint and broke `this.env` resolution in TouchstoneMcpAgent — every Workers file in this
// package uses the ambient global `Env` instead. TOUCHSTONE_ATTESTATION_KEY (the one real secret
// — see docs/listing.md and README.md for why it's the only one) is set via `wrangler secret
// put`, so it's part of the generated `Env` too even though it never appears in wrangler.jsonc.

export const GITHUB_REPO = "petrkrulis2022/dated-siu-inference";
export const GITHUB_RAW_BASE = `https://raw.githubusercontent.com/${GITHUB_REPO}/main`;
export const GITHUB_API_BASE = `https://api.github.com/repos/${GITHUB_REPO}`;
