import { Hono } from "hono";
import { createToolPaywall, extractToolCallName } from "../paywall.js";
import { getQuoteTool, type GetQuoteInput } from "../tools/get-quote.js";
import { createNodeShim } from "./node-shim.js";
import { TouchstoneMcpAgent } from "./mcp-agent.js";
import { githubDataSource } from "./data-source.js";
import { logToolCall } from "./analytics.js";

// `Env` here is the ambient global from worker-configuration.d.ts (generated by `wrangler
// types` — see env.ts's doc comment), not a locally declared type.

export { TouchstoneMcpAgent };

// Circle's gateway middleware is safe to build once and reuse across requests within the same
// isolate — TOUCHSTONE_SELLER_ADDRESS never changes for a given deploy, and constructing it
// fresh per request would redo whatever internal setup createGatewayMiddleware does for no
// benefit.
let paywall: ReturnType<typeof createToolPaywall> | undefined;

const app = new Hono<{ Bindings: Env }>();

function extractToolCallArguments(body: unknown): Record<string, unknown> | undefined {
  if (typeof body !== "object" || body === null) return undefined;
  const params = (body as Record<string, unknown>).params;
  if (typeof params !== "object" || params === null) return undefined;
  const args = (params as Record<string, unknown>).arguments;
  return typeof args === "object" && args !== null ? (args as Record<string, unknown>) : undefined;
}

/**
 * Runs get_quote's exact own computation ahead of the paywall, so a call that cannot succeed
 * never reaches it. Interim measure — see docs/methodology.md's "declared run-record manifest"
 * note: once publish time writes data/runs/<print_id>/index.json, get_quote stops depending on
 * GitHub's Contents API (the actual thing that can fail here) and this duplicate pre-check can
 * go. Until then: a buyer paying for a call that errors is the worst first impression this
 * service can give, so this trades one extra (cached) read for never charging for a failure.
 */
async function getQuoteWouldSucceed(args: Record<string, unknown>, env: Env): Promise<boolean> {
  try {
    const input = args as unknown as GetQuoteInput;
    const dataSource = githubDataSource(env.PRINTS_CACHE);
    const { print } = await dataSource.loadLatestPrint();
    const snapshot = await dataSource.loadPriceSnapshot(print.price_snapshot_ref);
    const allRecords = await dataSource.loadRunRecords(print.print_id);
    const modelRecords = allRecords.filter((r) => r.model_id === input.model);
    getQuoteTool(input, print, snapshot, modelRecords);
    return true;
  } catch {
    return false;
  }
}

/**
 * One route, exactly as the Node/Express deployment has — an MCP client always POSTs every tool
 * call to the same endpoint, so which tool is being called (and therefore whether payment is
 * required) can only be known by inspecting the JSON-RPC body, never the URL. The paywall dispatch
 * (../paywall.ts, unchanged, already tested) runs first via a minimal req/res shim
 * (./node-shim.js) — a real 402 challenge from Circle's real Gateway, not a reimplementation of
 * the x402 protocol. Only once payment clears (or the tool is free — createDispatcher's own
 * bypass, also unchanged) does the request reach the MCP layer, delegated to the McpAgent Durable
 * Object.
 */
app.post("/mcp", async (c) => {
  const bodyText = await c.req.text();
  let body: unknown;
  try {
    body = bodyText ? JSON.parse(bodyText) : undefined;
  } catch {
    body = undefined;
  }
  const toolName = extractToolCallName(body);

  if (toolName === "get_quote") {
    const args = extractToolCallArguments(body);
    if (args && !(await getQuoteWouldSucceed(args, c.env))) {
      // Skip the paywall entirely — forwarding straight to the MCP agent, unpaid, gives the
      // client the same correctly-formatted isError result get_quote would return anyway, for
      // free, instead of collecting a payment first and only then discovering the call fails.
      const mcpRequest = new Request(c.req.raw, { body: bodyText });
      return TouchstoneMcpAgent.serve("/mcp", { binding: "TOUCHSTONE_MCP" }).fetch(
        mcpRequest,
        c.env,
        c.executionCtx as unknown as ExecutionContext,
      );
    }
  }

  // Every other binding in this deployment (BASE_SEPOLIA_RPC_URL, TOUCHSTONE_ESCROW_ADDRESS) is
  // already Base-Sepolia-only, per wrangler.jsonc — createGatewayMiddleware's own default
  // facilitatorUrl is Circle's MAINNET Gateway, which would silently reject every testnet
  // payment rather than accept one, so this must be passed explicitly. Revisit alongside every
  // other testnet-only binding here when a mainnet deployment is ever built.
  paywall ??= createToolPaywall({
    sellerAddress: c.env.TOUCHSTONE_SELLER_ADDRESS,
    networks: ["eip155:84532"],
    facilitatorUrl: "https://gateway-api-testnet.circle.com",
  });
  const { req, res, next, settled, getResult, nextCalled, responseHeaders } = createNodeShim(
    c.req.raw,
    body,
  );
  // paywall(req, res, next) itself returns void synchronously (../paywall.ts's dispatchPaywall
  // calls the real middleware as `void middleware(...)`) — awaiting that resolves before Circle's
  // Gateway verify/settle call has done anything. `settled` is what actually waits for it.
  paywall(req, res, next);
  await Promise.race([
    settled,
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("paywall timed out")), 25_000),
    ),
  ]);

  if (!nextCalled()) {
    const result = getResult();
    return new Response(result?.body ?? "", {
      status: result?.status ?? 402,
      headers: result?.headers,
    });
  }

  // Observability must never be able to break the actual service — a write failure, or the
  // Analytics Engine binding being unavailable at all, is logged and swallowed, never thrown.
  if (toolName) {
    try {
      const payerAddress = (req as unknown as { payment?: { payer?: string } }).payment?.payer;
      logToolCall(c.env.USAGE, toolName, payerAddress);
    } catch (err) {
      console.error("usage logging failed:", err);
    }
  }

  // The original request's body was already fully consumed by c.req.text() above — a Request's
  // body stream can only be read once. Rebuild one carrying the same buffered text for the MCP
  // transport, which reads req.body itself.
  const mcpRequest = new Request(c.req.raw, { body: bodyText });
  // Hono's own ExecutionContext type is a narrower structural subset of
  // @cloudflare/workers-types' — both describe the same runtime object; McpAgent.serve()'s
  // .fetch() just wants the fuller shape.
  const mcpResponse = await TouchstoneMcpAgent.serve("/mcp", {
    binding: "TOUCHSTONE_MCP",
  }).fetch(mcpRequest, c.env, c.executionCtx as unknown as ExecutionContext);

  // A cleared payment's PAYMENT-RESPONSE header (the settlement receipt) was set on the shim's
  // throwaway res, not on the real response — carry it across, per the x402 protocol's own
  // expectation that a settled call's response includes it.
  const paymentResponseHeader = responseHeaders()["PAYMENT-RESPONSE"];
  if (paymentResponseHeader) {
    const withHeader = new Response(mcpResponse.body, mcpResponse);
    withHeader.headers.set("PAYMENT-RESPONSE", paymentResponseHeader);
    return withHeader;
  }
  return mcpResponse;
});

export default app;
