import { Hono } from "hono";
import { createToolPaywall, extractToolCallName } from "../paywall.js";
import { createNodeShim } from "./node-shim.js";
import { TouchstoneMcpAgent } from "./mcp-agent.js";
import { logToolCall } from "./analytics.js";

// `Env` here is the ambient global from worker-configuration.d.ts (generated by `wrangler
// types` — see env.ts's doc comment), not a locally declared type.

export { TouchstoneMcpAgent };

// Circle's gateway middleware is safe to build once and reuse across requests within the same
// isolate — TOUCHSTONE_SELLER_ADDRESS never changes for a given deploy, and constructing it
// fresh per request would redo whatever internal setup createGatewayMiddleware does for no
// benefit.
let paywall: ReturnType<typeof createToolPaywall> | undefined;

const app = new Hono<{ Bindings: Env }>();

/**
 * One route, exactly as the Node/Express deployment has — an MCP client always POSTs every tool
 * call to the same endpoint, so which tool is being called (and therefore whether payment is
 * required) can only be known by inspecting the JSON-RPC body, never the URL. The paywall dispatch
 * (../paywall.ts, unchanged, already tested) runs first via a minimal req/res shim
 * (./node-shim.js) — a real 402 challenge from Circle's real Gateway, not a reimplementation of
 * the x402 protocol. Only once payment clears (or the tool is free — createDispatcher's own
 * bypass, also unchanged) does the request reach the MCP layer, delegated to the McpAgent Durable
 * Object.
 */
app.post("/mcp", async (c) => {
  const bodyText = await c.req.text();
  let body: unknown;
  try {
    body = bodyText ? JSON.parse(bodyText) : undefined;
  } catch {
    body = undefined;
  }
  const toolName = extractToolCallName(body);

  // Every other binding in this deployment (BASE_SEPOLIA_RPC_URL, TOUCHSTONE_ESCROW_ADDRESS) is
  // already Base-Sepolia-only, per wrangler.jsonc — createGatewayMiddleware's own default
  // facilitatorUrl is Circle's MAINNET Gateway, which would silently reject every testnet
  // payment rather than accept one, so this must be passed explicitly. Revisit alongside every
  // other testnet-only binding here when a mainnet deployment is ever built.
  paywall ??= createToolPaywall({
    sellerAddress: c.env.TOUCHSTONE_SELLER_ADDRESS,
    networks: ["eip155:84532"],
    facilitatorUrl: "https://gateway-api-testnet.circle.com",
  });
  const { req, res, next, getResult, nextCalled, responseHeaders } = createNodeShim(
    c.req.raw,
    body,
  );
  await paywall(req, res, next);

  if (!nextCalled()) {
    const result = getResult();
    return new Response(result?.body ?? "", {
      status: result?.status ?? 402,
      headers: result?.headers,
    });
  }

  // Observability must never be able to break the actual service — a write failure, or the
  // Analytics Engine binding being unavailable at all, is logged and swallowed, never thrown.
  if (toolName) {
    try {
      const payerAddress = (req as unknown as { payment?: { payer?: string } }).payment?.payer;
      logToolCall(c.env.USAGE, toolName, payerAddress);
    } catch (err) {
      console.error("usage logging failed:", err);
    }
  }

  // The original request's body was already fully consumed by c.req.text() above — a Request's
  // body stream can only be read once. Rebuild one carrying the same buffered text for the MCP
  // transport, which reads req.body itself.
  const mcpRequest = new Request(c.req.raw, { body: bodyText });
  // Hono's own ExecutionContext type is a narrower structural subset of
  // @cloudflare/workers-types' — both describe the same runtime object; McpAgent.serve()'s
  // .fetch() just wants the fuller shape.
  const mcpResponse = await TouchstoneMcpAgent.serve("/mcp", {
    binding: "TOUCHSTONE_MCP",
  }).fetch(mcpRequest, c.env, c.executionCtx as unknown as ExecutionContext);

  // A cleared payment's PAYMENT-RESPONSE header (the settlement receipt) was set on the shim's
  // throwaway res, not on the real response — carry it across, per the x402 protocol's own
  // expectation that a settled call's response includes it.
  const paymentResponseHeader = responseHeaders()["PAYMENT-RESPONSE"];
  if (paymentResponseHeader) {
    const withHeader = new Response(mcpResponse.body, mcpResponse);
    withHeader.headers.set("PAYMENT-RESPONSE", paymentResponseHeader);
    return withHeader;
  }
  return mcpResponse;
});

export default app;
