import { McpAgent } from "agents/mcp";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createTouchstoneMcpServer } from "../server.js";
import { OnChainSettlementReader } from "../settlement/on-chain.js";
import { githubDataSource } from "./data-source.js";

// `Env` here is the ambient global from worker-configuration.d.ts (generated by `wrangler
// types` — see env.ts's doc comment), not a locally declared type.

/**
 * Cloudflare's documented pattern for a Streamable-HTTP MCP server on Workers (McpAgent, backed
 * by a Durable Object — see wrangler.jsonc's durable_objects binding + migration). `server` here
 * is built by the exact same `createTouchstoneMcpServer` the Node/Express deployment uses
 * (../server.js) — the tool registrations themselves are not re-implemented, only where they're
 * constructed from and what data source they read through (githubDataSource instead of the
 * fs-based default). This class holds no signing capability beyond
 * `TOUCHSTONE_ATTESTATION_KEY` (attests only, never anchors, never spends — see env.ts's doc
 * comment) and never writes anything, on-chain or to `data/`.
 */
export class TouchstoneMcpAgent extends McpAgent<Env, unknown, Record<string, never>> {
  server!: McpServer;

  async init(): Promise<void> {
    this.server = createTouchstoneMcpServer({
      attestationPrivateKeyHex: this.env.TOUCHSTONE_ATTESTATION_KEY,
      settlementReader: new OnChainSettlementReader({
        chainName: this.env.TOUCHSTONE_CHAIN_NAME,
        rpcUrl: this.env.BASE_SEPOLIA_RPC_URL,
        escrowAddress: this.env.TOUCHSTONE_ESCROW_ADDRESS,
      }),
      dataSource: githubDataSource(this.env.PRINTS_CACHE),
    });
  }
}
