/**
 * Which lab a run was made in. A change to what the lab IS — a rule an agent meets, a figure it is shown, a thing
 * the harness now refuses — makes a run before it a different instrument from a run after it, and the two are
 * never pooled (the gate configuration's reports carry the same kind of stamp). Bump the version and add a dated
 * line whenever such a change lands; `labDisqualification` excludes any run whose version is not this one.
 *
 * A change to how a run is MEASURED, or to the operator's side (the sweep, the report), is not one: it does not
 * alter what a trader meets.
 */
export const LAB_INSTRUMENT_VERSION = 7;

export const LAB_INSTRUMENT_CHANGES: readonly string[] = [
  "v1 2026-10-06: phase 1 as first built — T1 jobs, four traders, raw work from ISSUER-B, opening 2,000 mSIU and equal USDC, price parity with the dollar-route fee rebated.",
  "v2 2026-10-06: a quote may be paid only by the trader who asked for it, and once (lab/guards.ts). Before it a seller could pay its own quote by minting a claim for itself, and a quote could be paid twice by claim; found by the first model run, which therefore predates this and is not pooled.",
  "v3 2026-10-06: what a trader meets changed in four ways, all from the first model run (D26 to D28): the payment tools are named by what they do — pay_with_usdc, pay_with_new_claim, pay_with_held_claim, pay_split — with descriptions of one shape and one worked example each, and the loop's own names refused; a quote line leads with its request id alone (`qr-2: quote from seller …`); a payment the wallet cannot afford is refused before it is sent, in one sentence whichever asset it is in; and the spend projection uses measured output so the cap means what it says.",
  "v4 2026-10-07: the economy changed in five ways, all from the pilot and the first rerun (D30 to D35). Every payment is a direct transfer to the seller at the moment it is made, in either asset — no escrow, no fee, no rebate, no release step — so choosing an asset no longer chooses buyer protection or when the seller can spend. The opening is sized from the print and the schedule so that either asset alone meets every need, equal in value at the print (4,318 mSIU and 6,205 USDC minor units each at the print the pilot used; derived per run, not fixed), and nothing is minted after it: the fSIU supply is the endowment, fixed for the run. A payment may be drawn partly from a held claim and partly in USDC (pay_split). A refused payment states the whole wallet, in both assets, in one form. The brief states the three calls, what each costs, and that the supply is the opening supply. The motive structure is unchanged: the score counts fSIU at the print, and the lab has no route from fSIU to USDC.",
  "v5 2026-10-07: the roster, and nothing an agent is shown. The two gpt-5.4-mini seats are now claude-haiku-4-5 (D38): in the v4 rerun both stalled with work on their boards, and every need left unmet traced to one of them. The v4 rerun was made with the earlier roster and is not pooled with a run made with this one.",
  "v6 2026-10-07: the print moves between rounds, and the roster and the brief changed with it (D41 to D43). Each round after the first, the lab's print goes up or down by 15% with equal probability, from the run's seed — a scenario value used inside the lab only, never published, never the index; round 1 is the real print. A job is priced at 1.2 times the round's print and a unit of raw work at the print, so its price in USDC follows the print while a claim for it, sized at the print of the round the quote was asked for in, stays about 1 SIU (a job about 1.2). Each turn shows the print of every round so far and how far it moved, and the brief says the print can move; scoring is unchanged (USDC plus fSIU at the current print plus a credit, measured before the window closes). The opening is sized at the highest print the walk can reach, so either asset alone is still enough for every need; USDC is therefore worth more than the fSIU at round 1's print. `get_print` is gone (it reads the published print, which is not the lab's). The brief gains one line: valued at the current print, converting changes nothing about a result and is never required. The roster is again two families: claude-haiku-4-5 on TRADER-1 and TRADER-3, deepseek-v3.2 on TRADER-2 and TRADER-4 (it acted correctly on both screens the gpt-5.4-mini seats stalled on, five times in five). A v5 run, made with all four on haiku and a fixed print, is not pooled with a v6 run.",
  "v7 2026-10-07: the roster, and nothing an agent is shown. TRADER-2 is gpt-5.1 (OpenAI) and TRADER-4 grok-4.6 (xAI), both reached directly, in place of deepseek-v3.2 through OpenRouter (D47): the one v6 run was cut short when OpenRouter, a provider this lab had not used, answered 402 on a seat's twelfth turn. TRADER-1 and TRADER-3 stay claude-haiku-4-5. Both new models acted correctly, five times in five, on each of the two screens the gpt-5.4-mini seats had stalled on. A v6 run, made with deepseek, is not pooled with a v7 run (it is not countable anyway).",
];
