/**
 * Which lab a run was made in. A change to what the lab IS — a rule an agent meets, a figure it is shown, a thing
 * the harness now refuses — makes a run before it a different instrument from a run after it, and the two are
 * never pooled (the gate configuration's reports carry the same kind of stamp). Bump the version and add a dated
 * line whenever such a change lands; `labDisqualification` excludes any run whose version is not this one.
 *
 * A change to how a run is MEASURED, or to the operator's side (the sweep, the report), is not one: it does not
 * alter what a trader meets.
 */
export const LAB_INSTRUMENT_VERSION = 9;

export const LAB_INSTRUMENT_CHANGES: readonly string[] = [
  "v1 2026-10-06: phase 1 as first built — T1 jobs, four traders, raw work from ISSUER-B, opening 2,000 mSIU and equal USDC, price parity with the dollar-route fee rebated.",
  "v2 2026-10-06: a quote may be paid only by the trader who asked for it, and once (lab/guards.ts). Before it a seller could pay its own quote by minting a claim for itself, and a quote could be paid twice by claim; found by the first model run, which therefore predates this and is not pooled.",
  "v3 2026-10-06: what a trader meets changed in four ways, all from the first model run (D26 to D28): the payment tools are named by what they do — pay_with_usdc, pay_with_new_claim, pay_with_held_claim, pay_split — with descriptions of one shape and one worked example each, and the loop's own names refused; a quote line leads with its request id alone (`qr-2: quote from seller …`); a payment the wallet cannot afford is refused before it is sent, in one sentence whichever asset it is in; and the spend projection uses measured output so the cap means what it says.",
  "v4 2026-10-07: the economy changed in five ways, all from the pilot and the first rerun (D30 to D35). Every payment is a direct transfer to the seller at the moment it is made, in either asset — no escrow, no fee, no rebate, no release step — so choosing an asset no longer chooses buyer protection or when the seller can spend. The opening is sized from the print and the schedule so that either asset alone meets every need, equal in value at the print (4,318 mSIU and 6,205 USDC minor units each at the print the pilot used; derived per run, not fixed), and nothing is minted after it: the fSIU supply is the endowment, fixed for the run. A payment may be drawn partly from a held claim and partly in USDC (pay_split). A refused payment states the whole wallet, in both assets, in one form. The brief states the three calls, what each costs, and that the supply is the opening supply. The motive structure is unchanged: the score counts fSIU at the print, and the lab has no route from fSIU to USDC.",
  "v5 2026-10-07: the roster, and nothing an agent is shown. The two gpt-5.4-mini seats are now claude-haiku-4-5 (D38): in the v4 rerun both stalled with work on their boards, and every need left unmet traced to one of them. The v4 rerun was made with the earlier roster and is not pooled with a run made with this one.",
  "v6 2026-10-07: the print moves between rounds, and the roster and the brief changed with it (D41 to D43). Each round after the first, the lab's print goes up or down by 15% with equal probability, from the run's seed — a scenario value used inside the lab only, never published, never the index; round 1 is the real print. A job is priced at 1.2 times the round's print and a unit of raw work at the print, so its price in USDC follows the print while a claim for it, sized at the print of the round the quote was asked for in, stays about 1 SIU (a job about 1.2). Each turn shows the print of every round so far and how far it moved, and the brief says the print can move; scoring is unchanged (USDC plus fSIU at the current print plus a credit, measured before the window closes). The opening is sized at the highest print the walk can reach, so either asset alone is still enough for every need; USDC is therefore worth more than the fSIU at round 1's print. `get_print` is gone (it reads the published print, which is not the lab's). The brief gains one line: valued at the current print, converting changes nothing about a result and is never required. The roster is again two families: claude-haiku-4-5 on TRADER-1 and TRADER-3, deepseek-v3.2 on TRADER-2 and TRADER-4 (it acted correctly on both screens the gpt-5.4-mini seats stalled on, five times in five). A v5 run, made with all four on haiku and a fixed print, is not pooled with a v6 run.",
  "v7 2026-10-07: the roster, and nothing an agent is shown. TRADER-2 is gpt-5.1 (OpenAI) and TRADER-4 grok-4.6 (xAI), both reached directly, in place of deepseek-v3.2 through OpenRouter (D47): the one v6 run was cut short when OpenRouter, a provider this lab had not used, answered 402 on a seat's twelfth turn. TRADER-1 and TRADER-3 stay claude-haiku-4-5. Both new models acted correctly, five times in five, on each of the two screens the gpt-5.4-mini seats had stalled on. A v6 run, made with deepseek, is not pooled with a v7 run (it is not countable anyway).",
  "v8 2026-10-07: what an agent sees changed in four ways (D50). (1) A quote is denominated in SIU, as docs/datum-quote.md specifies: a job's price is 1.2 SIU and a unit of raw work's 1 SIU, in every round, and a request names that price as its siu and the round's print as its rate. The quote's dollars are the price in SIU times the print, at USDC's own six decimals rounded up to the next minor unit (not $0.0001 steps), so the dollars follow the print while the price in SIU does not, and paying in fSIU costs exactly the price in mSIU whatever the print. Each quote line leads with the work and its price in SIU, then what settling it costs in each asset at the round's print. (2) Each turn states what the trader holds, in both assets, each also in the other's terms at the print in force, read from the chain. (3) The order in which the payment routes and the two assets are listed is drawn from the run's seed and recorded in its report, so no route is always first. (4) The opening is derived from the schedule: the fSIU is exactly what the quotes in SIU come to, and the USDC pays every quote at the highest print the walk can reach. Scoring, the three payment routes, the print's walk and the D35 line are unchanged. Reporting and measurement also changed (the overview lists every transaction with the agent's stated reason and its raw reply, each provider's returned reasoning is captured without changing a model setting, and H2 is registered at the decision level, D51 to D53) but those do not alter what a trader meets. No earlier run saw a quote in SIU or its own fSIU holdings: none is a test of H1 or H2, and a v7 run is not pooled with a v8 run.",
  "v9 2026-10-09: the roster, and nothing an agent is shown but the model names in THE TRADERS (D57). All four seats are Anthropic, reached directly: claude-haiku-4-5 on TRADER-1 and TRADER-3, claude-sonnet-5 on TRADER-2 and TRADER-4, in place of gpt-5.1 (OpenAI) and grok-4.6 (xAI). The reason is spend, not behaviour: the daily print draws on OpenAI, xAI, Google and OpenRouter, and the lab now runs on the Anthropic credit alone. Sampling differs between the two models and is recorded per run, not assumed (D59, D60): claude-sonnet-5 accepts no temperature other than its default, so the two sonnet seats run at the provider's default sampling and not at the 0.7 the haiku seats use. The one v8 run, made with gpt-5.1 and grok-4.6, is not pooled with a v9 run.",
];
