/**
 * The overview every run's report carries (the user's standing request, 2026-10-07): who paid whom, for what, at what price, in which asset,
 * and — in the agent's own words — why. Generated from the run's report alone, so it can be regenerated by anyone holding the report, and
 * committed beside it.
 *
 * It states what happened and what each agent SAID. It draws no conclusion about why an agent chose what it chose: a stated reason is one
 * line the agent wrote after the fact, optional, and the raw reply is authoritative where they differ. Explanations belong to whoever reads
 * this, with the evidence in front of them; an overview that offered its own would be one more thing that quietly shapes the reading.
 */
import { decimalToUnits, unitsToDecimal } from "./money.js";
import { LAB_INSTRUMENT_VERSION } from "./instrument.js";
import { measureRun, labDisqualification, type MeasureReport, type RunMeasures } from "./measure.js";
import { rationaleCoverage, type DecisionRecord } from "./decisions.js";

/** A report as `runLab` writes it, with everything beyond what measurement needs optional, so an older report renders too. */
export interface OverviewReport extends Omit<MeasureReport, "sales"> {
  sales: { requestId: string; round?: number; kind: "trade" | "rawwork"; buyer: string; seller: string; needId?: string; quoted?: boolean; paid?: boolean; paidAsset?: string; delivered: boolean }[];
  models?: Record<string, string>;
  window?: { fromChainSeconds: string; toChainSeconds: string };
  turnsByAgent?: Record<string, number>;
  toolErrors?: { agentId: string; turn: number; tool: string; error: string }[];
  refusals?: { agentId: string; turn: number; kind: string; sentence: string }[];
  lag?: { writesRetried: number; recovered: number; gaveUp: number };
  spendByProvider?: Record<string, string>;
  decisions?: DecisionRecord[];
}

export interface OverviewOptions {
  /** Where the decisions came from, when they were not in the report itself: said at the top, so nobody reads a reconstruction as a record. */
  decisionsNote?: string;
}

const cell = (s: string | undefined): string => (s ?? "").replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
const usdcText = (minor: bigint): string => `${minor} USDC-minor`;
const PRINT_WORDS = /\bprint\b|hedge|\block(ed|ing)?\b|expir|conserv|cheaper|dearer|\bris(e|es|ing)\b|\bfall(s|ing)?\b|appreciat|depreciat|convert/i;

export function renderOverview(r: OverviewReport, options: OverviewOptions = {}): string {
  const m: RunMeasures = measureRun(r as unknown as MeasureReport);
  const labelOfSeat = Object.fromEntries(Object.entries(r.seats).map(([label, seat]) => [seat, label])) as Record<string, string>;
  // Only the traders decide: the issuer service's replies are a fixed policy's, with no model behind them and no reason to give.
  const decisions = (r.decisions ?? []).filter((d) => labelOfSeat[d.agentId] !== undefined);
  const who = (seat: string): string => labelOfSeat[seat] ?? seat;
  const moments = r.paymentMoments;
  const claimOf = new Map<string, string>();
  for (const e of r.capacityEvents) if (e.settlesRequestId !== undefined && e.quantityMilliSiu !== undefined) claimOf.set(e.settlesRequestId, e.quantityMilliSiu);
  const decisionAt = (agentId: string, turn: number | undefined): DecisionRecord | undefined => decisions.find((d) => d.agentId === agentId && d.turn === turn);
  const saleOf = new Map(r.sales.map((s) => [s.requestId, s]));
  const needOf = new Map(r.economy.needs.map((n) => [n.id, n as { id: string; buyer: string; seller: string; round: number; type?: string }]));
  const printOfRound = (round: number | undefined): bigint | undefined => (round === undefined || r.prints === undefined ? undefined : BigInt(r.prints.byRound[round - 1] ?? "0") || undefined);
  const movingPrint = (r.prints?.stepBps ?? 0) > 0;

  const out: string[] = [];
  // Two questions, kept apart: was it a sound run of its own instrument, and does it pool with runs under the current one?
  const ownReason = labDisqualification({ ...(r as unknown as MeasureReport), instrument: { version: LAB_INSTRUMENT_VERSION } });
  const poolReason = labDisqualification(r as unknown as MeasureReport);
  out.push(`# Run overview — ${r.runId}`, "");
  if (options.decisionsNote !== undefined) out.push(`> ${options.decisionsNote}`, "");
  out.push(
    `- **Seed ${r.seed}; instrument ${r.instrument?.version ?? "not stamped"}; ${r.scripted ? "a scripted walk (no model was called)" : "a model run"}.**`,
    `- **A sound run of its own instrument: ${ownReason === null ? "yes" : `NO — ${ownReason}`}.**`,
    `- **Pooled with runs under the current instrument (v${LAB_INSTRUMENT_VERSION}): ${poolReason === null ? "yes" : ownReason === null ? "no — made under another version" : "no"}.**`,
    ...(r.models !== undefined ? [`- Models: ${Object.entries(r.models).map(([t, mo]) => `${t} ${mo}`).join("; ")}.`] : []),
    ...(r.prints !== undefined
      ? [`- Print by round (nano-USD per SIU; a scenario value, step ${r.prints.stepBps} bps): ${r.prints.byRound.map((p, i) => `round ${i + 1} ${p}`).join(", ")}.`]
      : []),
    `- Cost $${m.costUsd}${r.spendByProvider !== undefined ? ` (${Object.entries(r.spendByProvider).filter(([, v]) => Number(v) > 0).map(([p, v]) => `${p} $${v}`).join(", ")})` : ""}.`,
    "",
    "## Headline",
    `- Needs met **${m.needsMet} of ${m.needsTotal}**. Opportunities **${m.opportunities}**, reused **${m.reuse}**, partial reuse ${m.partialReuse}.`,
    `- Payments: **${m.paymentsByRoute.usdc} in USDC, ${m.paymentsByRoute.held} from a held claim, ${m.paymentsByRoute.split} split**${m.paymentsByRoute.usdc + m.paymentsByRoute.held + m.paymentsByRoute.split === moments.length ? "" : " (some payments name no quote and are left out)"}.`,
    `- Waited while it had something it could do: **${m.waitedWithWork}** recorded wait(s).`,
    "",
  );

  // ---- every payment ---------------------------------------------------------------------------------------------------
  out.push("## Every payment, in the order it was made", "", "| # | Round asked / paid | Payer → payee | For | Price | Paid in | Delivered | Stated reason (the agent's own words) |", "|---|---|---|---|---|---|---|---|");
  let n = 0;
  for (const mo of moments) {
    const sale = mo.requestId === undefined ? undefined : saleOf.get(mo.requestId);
    if (sale === undefined || mo.quotedUsdMax === undefined) continue;
    n += 1;
    const need = sale.needId === undefined ? undefined : needOf.get(sale.needId);
    const what = sale.kind === "rawwork" ? "1 unit of raw work" : `a ${need?.type ?? "job"} job`;
    const priceMinor = decimalToUnits(mo.quotedUsdMax, 6);
    const asset = sale.paidAsset ?? "usdc";
    const claim = claimOf.get(sale.requestId);
    let paidIn: string;
    if (asset === "usdc") paidIn = `USDC (${usdcText(priceMinor)})`;
    else if (asset === "fsiu") paidIn = `fSIU (${claim ?? "?"} mSIU)`;
    else {
      const p = printOfRound(sale.round) ?? BigInt(0);
      const claimValue = claim !== undefined && p > 0n ? (BigInt(claim) * p) / 1_000_000n : undefined;
      paidIn = `USDC + fSIU (${claim ?? "?"} mSIU + ${claimValue === undefined ? "?" : usdcText(priceMinor - claimValue)})`;
    }
    const d = decisionAt(mo.agentId, mo.turn);
    const paidRound = d?.round;
    const rounds = `${sale.round !== undefined ? `r${sale.round}` : "?"} / ${paidRound !== undefined ? `r${paidRound}` : "?"}`;
    const payee = sale.seller === "ISSUER" ? "ISSUER-B" : sale.seller;
    const reason = d === undefined ? "(decision not recorded)" : d.rationale ?? "(none given)";
    out.push(`| ${n} | ${rounds} | ${who(mo.agentId)} → ${payee} | ${what} | $${mo.quotedUsdMax} | ${paidIn} | ${sale.kind === "trade" ? (sale.delivered ? "yes" : "NO") : "—"} | ${cell(reason)} |`);
  }
  if (n === 0) out.push("| — | | no payment was made | | | | | |");
  out.push("");

  const unpaid = r.sales.filter((s) => s.paid !== true);
  if (unpaid.length > 0) {
    out.push("## Asked for but never paid", "");
    for (const s of unpaid) out.push(`- ${s.requestId}: ${s.buyer} asked ${s.seller === "ISSUER" ? "ISSUER-B" : s.seller} for ${s.kind === "trade" ? "a job" : "a unit of raw work"}; ${s.quoted === true ? "it was quoted and not paid" : "it was never quoted"}.`);
    out.push("");
  }
  const unrequested = r.economy.needs.filter((nd) => !r.sales.some((s) => s.needId === nd.id));
  if (unrequested.length > 0) out.push(`Needs never even asked for: ${unrequested.map((nd) => `${nd.id} (${(nd as { type?: string }).type ?? "a job"} from ${nd.seller}, round ${nd.round})`).join("; ")}.`, "");

  // ---- per trader ------------------------------------------------------------------------------------------------------
  out.push("## Each trader", "", "| Trader | Model | Needs met | Paid in USDC | Paid from held fSIU | Split | fSIU: opened → ended | Result vs opening |", "|---|---|---|---|---|---|---|---|");
  for (const t of m.traders) {
    const open = r.snapshots[0]?.traders.find((x) => x.trader === t.trader);
    const end = r.final?.traders.find((x) => x.trader === t.trader);
    const usdc = t.jobsBoughtBy.usdc + t.rawBoughtBy.usdc;
    const held = t.jobsBoughtBy.held + t.rawBoughtBy.held;
    const split = t.jobsBoughtBy.split + t.rawBoughtBy.split;
    const delta = BigInt(t.resultNano) - BigInt(t.openingResultNano);
    out.push(
      `| ${t.trader} | ${r.models?.[t.trader] ?? "?"} | ${t.needsMet} | ${usdc} | ${held} | ${split} | ${open?.fsiuMilliSiu ?? "?"} → ${end?.fsiuMilliSiu ?? "?"} mSIU | ${delta >= 0n ? "+" : "−"}${unitsToDecimal(delta >= 0n ? delta : -delta, 9)} USD |`,
    );
  }
  out.push("");

  // ---- the print, and holdings against raw work still to buy ------------------------------------------------------------------
  if (movingPrint) {
    out.push("## fSIU held at each round's start, against the raw work still to buy (H2's raw material)", "", "| Trader | " + (r.prints?.byRound.map((_, i) => `Round ${i + 1}`).join(" | ") ?? "") + " |", "|---|" + (r.prints?.byRound.map(() => "---").join("|") ?? "") + "|");
    for (const t of m.traders) {
      const rows = m.holdings.filter((h) => h.trader === t.trader && h.label !== "final");
      out.push(`| ${t.trader} | ${rows.map((h) => `${((h.heldFraction ?? 0) * 100).toFixed(0)}% held (${h.fsiuMilliSiu} mSIU); ${h.upcomingRawUnits} unit(s) to buy`).join(" | ")} |`);
    }
    const c = m.h2.counts;
    out.push("", `With raw work still to buy: ${c.withN} trader-round(s), mean held ${c.withN ? ((c.withSum / c.withN) * 100).toFixed(1) : "n/a"}%. Without: ${c.withoutN}, mean held ${c.withoutN ? ((c.withoutSum / c.withoutN) * 100).toFixed(1) : "n/a"}%. One run has too few to read against H2's thresholds.`, "");
  }

  // ---- what they said about the print, holding, expiry, conserving ---------------------------------------------------------------
  const said = decisions.filter((d) => d.rationale !== undefined && PRINT_WORDS.test(d.rationale + " " + Object.values(d.friction ?? {}).join(" ")));
  out.push("## What traders said that mentions the print, holding, expiry or conserving (any call)", "");
  if (said.length === 0) out.push("- Nothing.");
  for (const d of said) out.push(`- ${who(d.agentId)}, ${d.round !== undefined ? `round ${d.round}, ` : ""}turn ${d.turn}, \`${d.tool}\`: ${cell(d.rationale)}`);
  out.push("");

  // ---- harness ---------------------------------------------------------------------------------------------------------
  out.push("## The harness", "");
  out.push(`- Turns: ${Object.entries(r.turnsByAgent ?? {}).map(([a, t]) => `${who(a)} ${t}`).join(", ") || "not recorded"}.`);
  out.push(`- How each seat ended: ${Object.entries(r.haltedReason ?? {}).map(([a, w]) => `${who(a)} ${w}`).join(", ") || "not recorded"}.`);
  const refusals = r.refusals ?? [];
  out.push(`- Refusals before a call ran: ${refusals.length}${refusals.length ? ":" : "."}`);
  for (const x of refusals) out.push(`  - ${who(x.agentId)} turn ${x.turn} (${x.kind}): ${cell(x.sentence).slice(0, 220)}`);
  const errs = r.toolErrors ?? [];
  out.push(`- Tool calls that errored: ${errs.length}${errs.length ? ":" : "."}`);
  for (const x of errs) out.push(`  - ${who(x.agentId)} turn ${x.turn} ${x.tool}: ${cell(x.error).slice(0, 220)}`);
  if (r.lag !== undefined) out.push(`- Writes that needed the node to catch up: ${r.lag.writesRetried} (${r.lag.recovered} recovered, ${r.lag.gaveUp} gave up).`);
  out.push("");

  // ---- the emphasis check ----------------------------------------------------------------------------------------------
  out.push("## Stated reasons: coverage, and the emphasis check", "");
  if (decisions.length === 0) {
    out.push("- No decisions are recorded for this run, so there are no stated reasons to show or check.");
  } else {
    const cov = rationaleCoverage(decisions);
    const pct = (c: { calls: number; withRationale: number }): string => `${c.withRationale} of ${c.calls}${c.calls ? ` (${Math.round((100 * c.withRationale) / c.calls)}%)` : ""}`;
    out.push(
      `- A rationale accompanied ${pct(cov.payments)} payment calls and ${pct(cov.others)} of every other call.`,
      `- By tool: ${Object.entries(cov.byTool).sort().map(([t, c]) => `${t} ${c.withRationale}/${c.calls}`).join(", ")}.`,
      cov.emphasis
        ? "- **EMPHASIS FLAG: payments carry a stated reason much more often than other calls. Check this before reading anything into the reasons: it is the emphasis effect, the option you instrument is the option you emphasise.**"
        : "- No emphasis effect: payments do not carry a stated reason noticeably more often than other calls.",
      "- The reasons are one optional line in the agent's own words, never required, validated or prompted for beyond one sentence that is the same for every tool. Where one differs from the raw reply, the raw reply is authoritative.",
      "- The field is present on almost every call, so its absence is rare and tells little here; what an agent chose to say is the information.",
    );
  }
  out.push("");
  return out.join("\n");
}
