import { Hono } from "hono";
import { cors } from "hono/cors";
import {
  type AnthropicContentBlock,
  type AnthropicMessage,
  callClaude,
  extractText,
  extractToolUses,
} from "../anthropic-client.js";
import {
  countDeclinedPaidCalls,
  countUnansweredInWeek,
  deleteOldConversations,
  ensureConversation,
  getLatestWeeklyDigest,
  getRecentMessages,
  getTodayCounts,
  getWeekUserMessages,
  insertWeeklyDigest,
  markStaleConversationsUnanswered,
  recordMessage,
  touchConversation,
} from "../db.js";
import { clusterCommonQuestions, findUnmetAsks } from "../digest.js";
import { looksLikeIndexQuestion, summarizeIndexWithoutLlm } from "../index-question.js";
import { fetchLiveIndex } from "../mcp-client.js";
import { callCostUsd, PER_TURN_RESERVATION_USD } from "../pricing.js";
import { bumpSessionUsage, checkAndBumpIpNewSessionLimit, checkSessionCap, hashIp } from "../rate-limit.js";
import { getConversation } from "../db.js";
import { isValidSessionId } from "../session-id.js";
import { stripSensitive } from "../pii.js";
import { buildSystemPrompt, CHAT_TOOLS } from "../system-prompt.js";
import { classifyVisitor } from "../visitor-type.js";
import { WIDGET_JS } from "../widget.js";

export { ChatBudgetTracker } from "./chat-budget-tracker.js";

// `Env` here is the ambient global from worker-configuration.d.ts (generated by `wrangler
// types`, hand-patched for ANTHROPIC_API_KEY — see that file's own doc comment), matching the
// convention already established in packages/mcp-server/src/workers/mcp-agent.ts.

const ALLOWED_ORIGINS = new Set(["https://prints.touchstoneassay.com", "https://console.touchstoneassay.com"]);
const MAX_MESSAGE_LENGTH = 2000;
const MAX_TOOL_ROUNDS = 3;
const HISTORY_LIMIT = 20;
const BUDGET_TRACKER_NAME = "global";

const app = new Hono<{ Bindings: Env }>();

app.use(
  "*",
  cors({
    origin: (origin) => (origin && ALLOWED_ORIGINS.has(origin) ? origin : ""),
  }),
);

app.get("/widget.js", (c) =>
  c.text(WIDGET_JS, 200, {
    "content-type": "application/javascript; charset=utf-8",
    "cache-control": "public, max-age=300",
  }),
);

interface ChatRequestBody {
  sessionId?: unknown;
  message?: unknown;
}

app.post("/chat", async (c) => {
  const body = (await c.req.json().catch(() => null)) as ChatRequestBody | null;
  if (!body || !isValidSessionId(body.sessionId) || typeof body.message !== "string" || !body.message.trim()) {
    return c.json({ error: "invalid request" }, 400);
  }
  const sessionId = body.sessionId;
  const message = body.message.trim().slice(0, MAX_MESSAGE_LENGTH);

  const ip = c.req.header("CF-Connecting-IP") ?? "unknown";
  const ipHash = await hashIp(ip);
  const userAgent = c.req.header("User-Agent") ?? null;
  const originOrReferer = c.req.header("Origin") ?? c.req.header("Referer") ?? null;
  const visitorType = classifyVisitor({ userAgent, originOrReferer, expectedOrigin: c.env.SITE_URL });

  const existing = await getConversation(c.env.CHAT_DB, sessionId);
  const now = new Date();

  if (!existing) {
    const ipCheck = await checkAndBumpIpNewSessionLimit(c.env.CHAT_LIMITS, ipHash, now);
    if (!ipCheck.allowed) {
      return c.json({ error: "Too many new conversations from this network in the last hour. Try again later." }, 429);
    }
  }

  const sessionCheck = await checkSessionCap(c.env.CHAT_LIMITS, sessionId);
  if (!sessionCheck.allowed) {
    return c.json(
      { reply: "This conversation has reached its message limit — refresh the page to start a new one." },
      429,
    );
  }

  await ensureConversation(c.env.CHAT_DB, sessionId, visitorType, ipHash, now.toISOString());
  await recordMessage(c.env.CHAT_DB, sessionId, "user", stripSensitive(message), now.toISOString());

  const budgetStub = c.env.CHAT_BUDGET.get(c.env.CHAT_BUDGET.idFromName(BUDGET_TRACKER_NAME));
  const reservation = await budgetStub.reserve(PER_TURN_RESERVATION_USD, c.env.CHAT_DAILY_CEILING_USD);

  if (!reservation.allowed) {
    const reply = await budgetExhaustedReply(c.env.MCP_SERVER_URL, message);
    await finishTurn(c.env.CHAT_DB, sessionId, reply, false);
    return c.json({ reply }, 200);
  }

  const history = await getRecentMessages(c.env.CHAT_DB, sessionId, HISTORY_LIMIT);
  const workingMessages: AnthropicMessage[] = history.map((m) => ({ role: m.role, content: m.content }));

  let quoteOffered = false;
  let totalInputTokens = 0;
  let totalOutputTokens = 0;
  let finalText = "";

  for (let round = 0; round < MAX_TOOL_ROUNDS; round++) {
    const response = await callClaude(
      c.env.ANTHROPIC_API_KEY,
      c.env.CHAT_MODEL,
      buildSystemPrompt(c.env.SITE_URL),
      workingMessages,
      CHAT_TOOLS,
    );
    totalInputTokens += response.usage.input_tokens;
    totalOutputTokens += response.usage.output_tokens;
    finalText = extractText(response);

    const toolUses = extractToolUses(response);
    if (response.stop_reason !== "tool_use" || toolUses.length === 0) break;

    workingMessages.push({ role: "assistant", content: response.content });
    const toolResults: AnthropicContentBlock[] = [];
    for (const use of toolUses) {
      if (use.name === "get_index") {
        try {
          const index = await fetchLiveIndex(c.env.MCP_SERVER_URL);
          toolResults.push({ type: "tool_result", tool_use_id: use.id, content: JSON.stringify(index) });
        } catch {
          toolResults.push({
            type: "tool_result",
            tool_use_id: use.id,
            content: "The live get_index lookup failed. Tell the visitor the lookup failed right now rather than stating any value.",
          });
        }
      } else {
        quoteOffered = true;
        toolResults.push({
          type: "tool_result",
          tool_use_id: use.id,
          content: `${use.name} cannot be executed here — it is a paid MCP tool. Tell the visitor to use the public MCP server (${c.env.MCP_SERVER_URL}) directly, listed at ${c.env.SITE_URL}/for-agents, to get a real one.`,
        });
      }
    }
    workingMessages.push({ role: "user", content: toolResults });
  }

  const actualCostUsd = callCostUsd({ input_tokens: totalInputTokens, output_tokens: totalOutputTokens });
  await budgetStub.reconcile(PER_TURN_RESERVATION_USD, actualCostUsd);
  await bumpSessionUsage(c.env.CHAT_LIMITS, sessionId, actualCostUsd);

  const reply = finalText.trim() || "I wasn't able to put together an answer — try rephrasing, or see the published methodology directly.";
  await finishTurn(c.env.CHAT_DB, sessionId, reply, quoteOffered);
  return c.json({ reply, quoteOffered }, 200);
});

async function finishTurn(db: D1Database, sessionId: string, reply: string, quoteOffered: boolean): Promise<void> {
  const nowIso = new Date().toISOString();
  await recordMessage(db, sessionId, "assistant", reply, nowIso);
  await touchConversation(db, sessionId, { lastMessageAt: nowIso, quoteOffered });
}

/** The daily budget is spent — no further LLM calls today. get_index is still free and real, so
 * a plain question about the current value still gets a real, live-fetched answer. */
async function budgetExhaustedReply(mcpServerUrl: string, message: string): Promise<string> {
  if (looksLikeIndexQuestion(message)) {
    try {
      const index = await fetchLiveIndex(mcpServerUrl);
      return summarizeIndexWithoutLlm(index);
    } catch {
      // fall through to the plain refusal below
    }
  }
  return "Today's chat budget has been reached. The published print is always available directly at prints.touchstoneassay.com — please try again tomorrow.";
}

app.get("/digest", async (c) => {
  const latest = await getLatestWeeklyDigest(c.env.CHAT_DB);
  const todayStart = new Date();
  todayStart.setUTCHours(0, 0, 0, 0);
  const today = await getTodayCounts(c.env.CHAT_DB, todayStart.toISOString());
  const budgetStub = c.env.CHAT_BUDGET.get(c.env.CHAT_BUDGET.idFromName(BUDGET_TRACKER_NAME));
  const spentToday = await budgetStub.spentToday();

  return c.json({
    latest_weekly_digest: latest
      ? {
          week_start: latest.week_start,
          common_questions: JSON.parse(latest.common_questions) as string[],
          unmet_asks: JSON.parse(latest.unmet_asks) as string[],
          declined_paid_calls: latest.declined_paid_calls,
          unanswered_conversations: latest.unanswered_conversations,
          generated_at: latest.generated_at,
        }
      : null,
    today: { conversations: today.conversations, messages: today.messages, spent_usd: spentToday },
  });
});

export default {
  fetch: app.fetch,
  async scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(runWeeklyDigest(env));
  },
};

const RETENTION_DAYS = 90;
const STALE_UNANSWERED_MINUTES = 30;

/** Sunday 02:00 UTC, per wrangler.jsonc's cron trigger. Computes the just-finished week
 * (Sunday 00:00 UTC to the moment this runs) rather than a calendar week ending in the future. */
async function runWeeklyDigest(env: Env): Promise<void> {
  const now = new Date();
  const weekEnd = now.toISOString();
  const weekStartDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const weekStart = weekStartDate.toISOString();

  const staleBefore = new Date(now.getTime() - STALE_UNANSWERED_MINUTES * 60 * 1000).toISOString();
  await markStaleConversationsUnanswered(env.CHAT_DB, staleBefore);

  const weekMessages = await getWeekUserMessages(env.CHAT_DB, weekStart, weekEnd);
  const [commonQuestions, declinedPaidCalls, unansweredConversations] = await Promise.all([
    clusterCommonQuestions(env.ANTHROPIC_API_KEY, env.CHAT_MODEL, weekMessages),
    countDeclinedPaidCalls(env.CHAT_DB, weekStart, weekEnd),
    countUnansweredInWeek(env.CHAT_DB, weekStart, weekEnd),
  ]);
  const unmetAsks = findUnmetAsks(weekMessages);

  await insertWeeklyDigest(env.CHAT_DB, {
    week_start: weekStart,
    common_questions: JSON.stringify(commonQuestions),
    unmet_asks: JSON.stringify(unmetAsks),
    declined_paid_calls: declinedPaidCalls,
    unanswered_conversations: unansweredConversations,
    generated_at: now.toISOString(),
  });

  const retentionCutoff = new Date(now.getTime() - RETENTION_DAYS * 24 * 60 * 60 * 1000).toISOString();
  await deleteOldConversations(env.CHAT_DB, retentionCutoff);
}
