/**
 * The sandboxed runner, as a plain JS source string rather than a compiled sibling file.
 * grade.ts writes this into the same temp directory as candidate.mjs/tests.json on every
 * call and runs it there — this decouples the sandbox from build order entirely: it works
 * identically whether grade.ts itself is loaded from compiled dist/ or, under vitest,
 * straight from TS source (where no compiled sandbox-runner.js sibling exists yet).
 */
export const RUNNER_SOURCE = [
  'import { readFileSync } from "node:fs";',
  'import { join } from "node:path";',
  'import { pathToFileURL } from "node:url";',
  "",
  "async function main() {",
  "  const cwd = process.cwd();",
  "  let spec;",
  "  try {",
  '    spec = JSON.parse(readFileSync(join(cwd, "tests.json"), "utf-8"));',
  "  } catch (e) {",
  '    console.log(JSON.stringify({ passed: false, error: "Could not read tests.json: " + String(e) }));',
  "    return;",
  "  }",
  "",
  "  let mod;",
  "  try {",
  '    mod = await import(pathToFileURL(join(cwd, "candidate.mjs")).href);',
  "  } catch (e) {",
  '    console.log(JSON.stringify({ passed: false, error: "Candidate module failed to load: " + String(e) }));',
  "    return;",
  "  }",
  "",
  "  const fn = mod[spec.functionName];",
  '  if (typeof fn !== "function") {',
  "    console.log(",
  '      JSON.stringify({ passed: false, error: "No exported function named \\"" + spec.functionName + "\\" found." }),',
  "    );",
  "    return;",
  "  }",
  "",
  "  const results = spec.testCases.map((testCase, index) => {",
  "    try {",
  "      const actual = fn(...testCase.args);",
  "      const passed = JSON.stringify(actual) === JSON.stringify(testCase.expected);",
  "      return { index, passed, actual, expected: testCase.expected };",
  "    } catch (e) {",
  "      return { index, passed: false, error: String(e) };",
  "    }",
  "  });",
  "",
  "  console.log(JSON.stringify({ passed: results.every((r) => r.passed), results }));",
  "}",
  "",
  "main();",
  "",
].join("\n");
